In [2]:
import numpy as np
print(np)

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>


In [4]:
x = np.arange(15) # 2-D array
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
x = np.arange(15,dtype=np.int64)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
x = x.reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
x[1:, ::2]

array([[ 5,  7,  9],
       [10, 12, 14]])

In [13]:
x[2:, :3]

array([[10, 11, 12]])

In [16]:
x[1:, ::2] = -99
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]])

In [23]:
x.max(axis=0) # dimension 1


array([ 0, 11,  2, 13,  4])

In [24]:
x.max(axis=1) # dimension 2

array([ 4,  8, 13])

In [25]:
# random number generating
rng = np.random.default_rng()
rng

Generator(PCG64) at 0x7CF08165D540

In [28]:
samples = rng.normal(size=10)
samples



array([-1.65829008,  0.98561593, -1.74133549, -0.09514157, -1.28836358,
       -0.9322649 ,  0.57309647,  0.73874232,  0.18586968, -1.5037801 ])

In [30]:
samples[::5]

array([-1.65829008, -0.9322649 ])